name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Build-Image-Docker
      run: docker build ./Mensageria -t brunobentocaina/open-adm-mensageria:latest
    - name: Push
      run: |
        docker login -u brunobentocaina -p ${{ secrets.DOCKER_HUB_KEY }}
        docker push brunobentocaina/open-adm-mensageria:latest
